services:
  scraper:
    image: getmeili/docs-scraper:latest
    container_name: scraper
    command: pipenv run ./docs_scraper config.json -d
    depends_on:
      - search
    environment:
      - MEILISEARCH_HOST_URL=localhost:7700
      - MEILISEARCH_API_KEY=""
    volumes:
      - ./scraper:/data.ms

  search:
    image: getmeili/meilisearch:latest
    container_name: search
    ports:
      - 7700:7700
    volumes:
      - search_db:/home/db

volumes:
  search_db:
