packages:
    - "packages/**"
    # excludes test dirs and node_modules
    - "!**/test/**"
    - "!**/node_modules/**"
# [Ref](https://pnpm.io/workspaces#shared-workspace-lockfile)
shared-workspace-lockfile: true
