# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

on:
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: eslint
      run: |
        pnpm run lint