# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Test

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Prep Env
      uses: ./prep
    - name: Lint
      run: pnpm run lint
    - name: unit tests
      run: pnpm run test
        