# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Test
description: run linter and unit tests on all packages

on:
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: ./atomic/build
    - name: Lint
      uses: ./atomic/lint
    - name: unit tests
      run: pnpm run test
        